# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 山不辞土 故能成其高
email: admin@zengde.net
description: > # this means to ignore newlines until "baseurl:"
  zengde的个人博客站。内容主要以php,javascript,jquery,html,css,与IT有关文章为主。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zengde.net" # the base hostname & protocol for your site
twitter_username: zengde
github_username:  zengde

# Build settings
markdown: kramdown
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]
paginate: 10
exclude: ["nbproject"]